### ISSUE TITLE
Exercise 4: "A Practical Introduction to Working with Medical Image Data"

### ISSUE THREAD

**Issue by thompson318** [HealthBioscienceIDEAS/Medical-Image-Registration-Short-Course#4]

**Comment by mxochicale** [comment]
@milanmlft @davecash75 @thompson318  

I have created a scaffold file for a new episode (e.g. [itksnap.Rmd](https://github.com/HealthBioscienceIDEAS/Medical-Image-Registration-Short-Course/blob/4-excercise4/episodes/itksnap.Rmd) which is part of this branch [`4-excercise4`](https://github.com/HealthBioscienceIDEAS/Medical-Image-Registration-Short-Course/tree/4-excercise4))

* Is there a way to preview it locally (without push it to the repo)? 
* Am I missing something to see [itksnap.Rmd](https://github.com/HealthBioscienceIDEAS/Medical-Image-Registration-Short-Course/blob/4-excercise4/episodes/itksnap.Rmd) in https://healthbioscienceideas.github.io/Medical-Image-Registration-Short-Course/ ?

Thanks, Miguel

**Comment by milanmlft** [comment]
- You can run `sandpaper::build_lesson()` from R to build the lesson locally, or `sandpaper::serve()` to get a live preview (which will retrigger whenever you make changes, very handy when writing content)
- You'll need to add the episode filename to the `episodes` field in `config.yaml` to get a link to it on the homepage, the order of the `episodes` list will determine the order in which episodes appear in the menu

Hope that helps!

**Comment by mxochicale** [comment]
Thanks @milanmlft  

Should my feature branch be merged to the main as it seems the page does not exist https://healthbioscienceideas.github.io/Medical-Image-Registration-Short-Course/itksnap.html after this changes  [3e4de68](https://github.com/HealthBioscienceIDEAS/Medical-Image-Registration-Short-Course/commit/3e4de681491d292b008cb28747b6f6ebc720e616) and tried with my feature branch [d76b1f3](https://github.com/HealthBioscienceIDEAS/Medical-Image-Registration-Short-Course/commit/d76b1f3d00b17ad702e5e86baecdbf6547b079b0) ?

**Comment by milanmlft** [comment]
> Should my feature branch be merged to the main as it seems the page does not exist [healthbioscienceideas.github.io/Medical-Image-Registration-Short-Course/itksnap.html](https://healthbioscienceideas.github.io/Medical-Image-Registration-Short-Course/itksnap.html) after this changes [3e4de68](https://github.com/HealthBioscienceIDEAS/Medical-Image-Registration-Short-Course/commit/3e4de681491d292b008cb28747b6f6ebc720e616) and tried with my feature branch [d76b1f3](https://github.com/HealthBioscienceIDEAS/Medical-Image-Registration-Short-Course/commit/d76b1f3d00b17ad702e5e86baecdbf6547b079b0) ?

Yes! If you want a preview of your episode, you can always build the website locally with `sandpaper::build_lesson()`

**Comment by mxochicale** [comment]
@jamie-mcclelland have a look to the nibabel examples https://healthbioscienceideas.github.io/Medical-Image-Registration-Short-Course/itksnap.html

**Comment by jamie-mcclelland** [comment]
@mxochicale great work on implementing my previous suggestions.
I'm afraid I only managed a quick look over the nibabel part of the exercises today as some other things came up - from what I could see all the code snippets etc looked good, but a lot of the text instructions from the pdf have not been copied over, and most (if not all) of these are needed to understand the code snippets and the concepts/issues we are trying to teach in the lesson
I will try and spend a bit of time tomorrow looking in more detail at exactly what text needs to be copied where (although not sure how to make that clear in a comment - would it make sense to do another pull request for me to review like last time?) - however, as there is good correspondence between the code snippets in the sandpaper and my pdf, it should be fairly clear where most of the text from the pdf instructions needs to go. And while there probably are a few bits of text that could be removed, the rule of thumb should be that all of the text from the pdf gets copied over (unless it applies to something that has changes, e.g. installation instructions)

**Comment by davecash75** [comment]
HI @mxochicale just to let you know I've created a [new branch](/HealthBioscienceIDEAS/Medical-Image-Registration-Short-Course/tree/nibabel-updates) for adding the instructions explaining what the code snippets can do (found in @jamie-mcclelland's PDF). If some of those could be copied over to the appropriate places in the markdown, that would be really appreciated.

**Comment by jamie-mcclelland** [comment]
@mxochicale - I have been looking at the nibabel part of exercises 4, and back at the updated itk part, and am confused about exactly which data is being used where, as the screenshots and nifti header to not appear as expected. I realise that the plans for this have changed as time has gone on, and my comments on the pull request may not have made it super clear what should be used where.
we want to use 4 of the images from the TCIA dataset for these exercises. these will all come from CT-PET-VI-02. Prior to sharing the data with the students we will put the data into folders with simpler and more informative names.
5.000000-Thorax Insp  2.0  B70f-29873 will be put in a folder called inhale_BH_CT
7.000000-Thorax Exp  2.0  B70f-73355 will be put in a folder called exhale_BH_CT
3.000000-CT Lung  3.0  B31f-61322 will be put in a folder called CT_for_PET
4.000000-Galligas Lung-03537 will be put in a folder called PET
In the exercises instructions on sandpaper we can then just refer to the images by these folder names, and do not need to use the original long and confusing names. as we discussed yesterday we can add some extra instructions (linked to but separate from the main instructions) explaining that if the reader does not have the data we have shared with them directly they can download it directly from TCIA - I can't remember if the TCIA downloader makes it possible to download individual subjects or even scans from their datasets - if so they can just download the required subject/scan, if not they will need to download everything - we can then instruct them to rename the folders to the names above, and they can then follow the main instructions exactly like the students we give the data to.
The instructions should provide a brief explanation of what each scan is, e.g.:
inhale_BH_CT and exhale_BH_CT contain CT scans acquired during an inhalation breath hold and exhalation breath hold respectively.
PET contains a PET scan that measures the local lung function, and CT_for_PET contains a CT scan acquired at the same time as the PET scan for attenuation correction of the PET scan and to provide anatomical reference for the PET data.
Then, for the itk-snap parts, we should use the inhale_BH_CT and exhale_BH_CT as the initial two images where we demonstrate navigation and flipping between 2 images (it looks like you may have used CT_for_PET, i.e. 3.0000-CT... for part of this)
For the colour overlay demo we should load CT_for_PET as the main image, and PET as the colour overlay, with the result looking something like this:
![image](https://github.com/HealthBioscienceIDEAS/Medical-Image-Registration-Short-Course/assets/9380572/e88fc338-841d-4ac9-9027-5c5835515a37)
(which i now see looks the same as the screenshots you have for the layer inspector tools, but not for loading and displaying the colour overlay)
I don't think we need the bit on loading an image in a second window, so when it gets to saving the dicom as a nifti the students should still have CT_for_PET and PET as the images currently loaded. We should then specify that they save the CT_for_PET image, and give it the name CT_for_PET.nii.gz (explaining that adding the .gz will save it as a compressed file which saves space and can still be read directly by most software - as explained in the original instructions).
Your code snippets seem to imply this was the image you saved - however, the nifti header is different to what I get when I save this image as a nifti and then read it using nibabel. As the idea is to get the students to look carefully at the header as read by nibabel, and that in itk-snap, and compare them, it is important the header is correct and as expected.

I think addressing the above issue, so that the correct data is used in the correct places, is the main priority to address for these exercises in the remaining time. If there is any extra time, this can be spent transferring some of the text from the ipmi instruction pdf into the sandpaper at the relevant places, although some of this will need modifying and updating to reflect the different data and use of itksnap instead of niftyview - but I can finish this off in the future when I find more time (as I will likely want to make my own edits to it anyway) so do not worry if this is not completed before the project finishes.
Hope that is all good and makes sense, but let me know if not or if you have any questions

**Comment by jamie-mcclelland** [comment]
forgot to add, I have prepared the data as it should be shared with the students and its available in the shared folder with the ipmi exercises here: https://liveuclac-my.sharepoint.com/:f:/r/personal/rmapjrm_ucl_ac_uk/Documents/IPMI%20course/2023-24%20material/exercises/[data_for_IDEAS_short_course](https://liveuclac-my.sharepoint.com/:f:/r/personal/rmapjrm_ucl_ac_uk/Documents/IPMI%20course/2023-24%20material/exercises/data_for_IDEAS_short_course?csf=1&web=1&e=AIYfEz)?csf=1&web=1&e=AIYfEz

**Comment by mxochicale** [comment]
@davecash75  For branch naming, I suggest this notation "git checkout -b ISSUENUMBER-branch-name" already in the main in our [contributions guidelines](https://github.com/HealthBioscienceIDEAS/Medical-Image-Registration-Short-Course/blob/main/CONTRIBUTING.md#committing-and-pushing-changes). So, I am starting a new branch `14-nibabel-requests` addressing above comments and avoid using https://github.com/HealthBioscienceIDEAS/Medical-Image-Registration-Short-Course/commit/9a96b94ed54c13570697e6e81e2ab9f82274a32c which mainly contain request points. Will raise soon reviews with relevant PR
> HI @mxochicale just to let you know I've created a [new branch](/HealthBioscienceIDEAS/Medical-Image-Registration-Short-Course/tree/nibabel-updates) for adding the instructions explaining what the code snippets can do (found in @jamie-mcclelland's PDF). If some of those could be copied over to the appropriate places in the markdown, that would be really appreciated.
